//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_client.MyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReference.MyServiceSoap")]
    public interface MyServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloServiceResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloService", ReplyAction="*")]
        web_client.MyServiceReference.HelloServiceResponse HelloService(web_client.MyServiceReference.HelloServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloService", ReplyAction="*")]
        System.Threading.Tasks.Task<web_client.MyServiceReference.HelloServiceResponse> HelloServiceAsync(web_client.MyServiceReference.HelloServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloService", Namespace="http://tempuri.org/", Order=0)]
        public web_client.MyServiceReference.HelloServiceRequestBody Body;
        
        public HelloServiceRequest() {
        }
        
        public HelloServiceRequest(web_client.MyServiceReference.HelloServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloServiceRequestBody {
        
        public HelloServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_client.MyServiceReference.HelloServiceResponseBody Body;
        
        public HelloServiceResponse() {
        }
        
        public HelloServiceResponse(web_client.MyServiceReference.HelloServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloServiceResult;
        
        public HelloServiceResponseBody() {
        }
        
        public HelloServiceResponseBody(string HelloServiceResult) {
            this.HelloServiceResult = HelloServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceSoapChannel : web_client.MyServiceReference.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<web_client.MyServiceReference.MyServiceSoap>, web_client.MyServiceReference.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_client.MyServiceReference.HelloServiceResponse web_client.MyServiceReference.MyServiceSoap.HelloService(web_client.MyServiceReference.HelloServiceRequest request) {
            return base.Channel.HelloService(request);
        }
        
        public string HelloService() {
            web_client.MyServiceReference.HelloServiceRequest inValue = new web_client.MyServiceReference.HelloServiceRequest();
            inValue.Body = new web_client.MyServiceReference.HelloServiceRequestBody();
            web_client.MyServiceReference.HelloServiceResponse retVal = ((web_client.MyServiceReference.MyServiceSoap)(this)).HelloService(inValue);
            return retVal.Body.HelloServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web_client.MyServiceReference.HelloServiceResponse> web_client.MyServiceReference.MyServiceSoap.HelloServiceAsync(web_client.MyServiceReference.HelloServiceRequest request) {
            return base.Channel.HelloServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<web_client.MyServiceReference.HelloServiceResponse> HelloServiceAsync() {
            web_client.MyServiceReference.HelloServiceRequest inValue = new web_client.MyServiceReference.HelloServiceRequest();
            inValue.Body = new web_client.MyServiceReference.HelloServiceRequestBody();
            return ((web_client.MyServiceReference.MyServiceSoap)(this)).HelloServiceAsync(inValue);
        }
    }
}
